### ISSUE TITLE
problem connecting to github

### ISSUE THREAD

**Issue by jennamanto** [fullstackjournalists/fullstackjournalists#6]
Last login: Fri Mar 30 17:46:34 on ttys000
dhcp-wifi-8021x-168-122-0-120:~ jennamanto$ git clone git@github.com:jennamanto/fullstackjournalists.git
Cloning into 'fullstackjournalists'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
dhcp-wifi-8021x-168-122-0-120:~ jennamanto$ sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...
dhcp-wifi-8021x-168-122-0-120:~ jennamanto$ sudo -su
sudo: option requires an argument -- u
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...
dhcp-wifi-8021x-168-122-0-120:~ jennamanto$ sudo -u
sudo: option requires an argument -- u
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...
dhcp-wifi-8021x-168-122-0-120:~ jennamanto$ sudo -s
Password:
Sorry, try again.
Password:
bash-3.2# git clone git@github.com:jennamanto/fullstackjournalists.git
Cloning into 'fullstackjournalists'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
bash-3.2#

**Comment by lisawilliams** [comment]
Hey Jenna -- 

Just googling around about the problem and found this: https://github.com/kenzanlabs/million-song-library/issues/347

So, there are three different ways to get a repo from Github onto your computer: via HTTPS, via SSH, and via downloading a ZIP file of the repository.  

SSH is the most secure. Instead of passwords, the client (you) and the server (whatever you're communicating with) use something called public key encryption to verify that you're both who you say you are (more on this here if you are interested: http://blog.robertelder.org/what-is-ssh/)

For our purposes, we don't *need* to use SSH for what we're doing. We can use HTTPS, which won't require you to set up public key encryption.  

So what I'm going to recommend that you do is to clone the folder again. Click the "clone or download" button in the upper right and make sure it says "Clone with HTTPS." Grab that url and at the command line, type `git clone [url you paste from the repository]`.  It should work -- if it doesn't, get back to me, ok?

**Comment by lisawilliams** [comment]
Hey, Jenna -- since you were able to add yourself to the members.md file, I'm going to assume that your git problems are solved. Yay! I'm going to close this issue for now but feel free to reopen it if you're still having difficulties.
